### ISSUE TITLE
Tests fail randomly with async:true

### ISSUE THREAD

**Issue by mayoms** [bbalser/Placebo#13]
👋 It seems Placebo does not support async testing -- or am I missing something?

The documentation makes no reference to whether or not tests should be synchronous, or if there is a way to make it async?

See [mecks_unit](https://github.com/archan937/mecks_unit) for an example of a wrapper that supports async. I may have to switch, though I do prefer being able to validate method calls and the style of Placebo.

**Comment by jdenen** [comment]
Hi @mayoms. Thanks for bringing this up. The project @bbalser and I use placebo in doesn't typically run tests asynchronously, so I think this just slipped our attention.

We're going to take a look at fixing over the weekend.

**Comment by jdenen** [comment]
@mayoms We just released `2.0.0-rc1`. We need to make documentation changes before that becomes a proper release, but we don't expect more code changes around it.

Give that a shot and let us know what you think.

**Comment by mayoms** [comment]
@jdenen was able to circle back to this today. works great. 👍

**Comment by jdenen** [comment]
That's awesome to hear. I'm going to close this issue and we'll push a proper release version soon.

**Comment by mayoms** [comment]
@jdenen @bbalser any status on this being released?

**Comment by jdenen** [comment]
Hey @mayoms. Thanks for pushing on this. It totally slipped our minds. I'm going to update the docs and release today.

**Comment by mayoms** [comment]
awesome, thanks @jdenen
